In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
                [4, 5, 6]])

In [3]:
a.sum(axis=0)
# Column wise  

array([5, 7, 9])

In [4]:
a.sum(axis=1)
# row wise

array([ 6, 15])

In [5]:
b = np.array([[7, 8, 0],
                [4, 0, 6]])

In [7]:
a.dot(b.transpose())

array([[23, 22],
       [68, 52]])

In [10]:
len(dir(np))

593

Cross Product

In [11]:
np.cross(a, b)

array([[-24,  21,  -6],
       [ 30,   0, -20]])

In [12]:
np.dot(a, b.transpose())

array([[23, 22],
       [68, 52]])

# Sorting

In [18]:
a = np.array([[11, 21, 3],
                [4, 15, 66]])

In [16]:
np.sort(a)

array([[ 3, 11, 21],
       [ 4, 15, 66]])

In [22]:
%%time
np.sort(a, axis=0, kind='mergesort')

CPU times: total: 0 ns
Wall time: 0 ns


array([[ 4, 15,  3],
       [11, 21, 66]])