In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [12]:
b = np.array([1,34,56,4,6,9,3,98,40,67,56,63,23,16,6,95])
b = b.reshape(8, 2)
b

array([[ 1, 34],
       [56,  4],
       [ 6,  9],
       [ 3, 98],
       [40, 67],
       [56, 63],
       [23, 16],
       [ 6, 95]])

In [18]:
np.argsort(b, axis=0)

array([[0, 1],
       [3, 2],
       [2, 6],
       [7, 0],
       [6, 5],
       [4, 4],
       [1, 7],
       [5, 3]], dtype=int64)

In [14]:
np.argmin(b)

0

In [15]:
np.argmax(b)

7