In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3, 4, 5]

In [3]:
arr = np.arange(1000000) 

In [4]:
pythlist = list(range(1000000))

In [5]:
%time for _ in range(10): [item *3 for item in pythlist]

CPU times: total: 1.53 s
Wall time: 1.62 s


In [6]:
%time for _ in range(10): arr = arr*3

CPU times: total: 93.8 ms
Wall time: 78 ms


In [7]:
array1 = np.array([[1, 2, 3, 4, 5],[6, 7, 8 , 9,10]])
print(array1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
array1.shape

(2, 5)

In [9]:
array1.dtype

dtype('int32')

In [10]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones(4).dtype

dtype('float64')

In [12]:
np.empty((4,6))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219714e-306, 1.89146896e-307, 7.56571288e-307],
       [3.11525958e-307, 1.24610723e-306, 1.37962320e-306,
        1.29060871e-306, 2.22518251e-306, 1.33511969e-306],
       [1.78022342e-306, 1.05700345e-307, 3.11525958e-307,
        1.69118108e-306, 8.06632139e-308, 1.20160711e-306],
       [1.69119330e-306, 1.29062229e-306, 8.45590539e-307,
        9.34607074e-307, 8.01097889e-307, 2.56765117e-312]])

In [13]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Slicing

In [30]:
array2 = np.array([ 6,  7,  8,  9, 10])

In [31]:
arr = array2[4:6]

In [32]:
arr

array([10])

In [33]:
array2

array([ 6,  7,  8,  9, 10])